steps:
  - name: 'gcr.io/k8s-skaffold/skaffold'
    args: [
        'gcloud', 'container', 'clusters', 'get-credentials', 'keybons',
        '--zone', 'us-west2-b', '--project', 'keybons'
    ]
  - name: 'gcr.io/k8s-skaffold/skaffold'
    args: [ 'skaffold','run' ]